package cz.mg.vulkan.enums;

import cz.mg.vulkan.jna.enums.VkStructureType;


public enum VulkanStructureType {
    APPLICATION_INFO,
    INSTANCE_CREATE_INFO,
    DEVICE_QUEUE_CREATE_INFO,
    DEVICE_CREATE_INFO,
    SUBMIT_INFO,
    MEMORY_ALLOCATE_INFO,
    MAPPED_MEMORY_RANGE,
    BIND_SPARSE_INFO,
    FENCE_CREATE_INFO,
    SEMAPHORE_CREATE_INFO,
    EVENT_CREATE_INFO,
    QUERY_POOL_CREATE_INFO,
    BUFFER_CREATE_INFO,
    BUFFER_VIEW_CREATE_INFO,
    IMAGE_CREATE_INFO,
    IMAGE_VIEW_CREATE_INFO,
    SHADER_MODULE_CREATE_INFO,
    PIPELINE_CACHE_CREATE_INFO,
    PIPELINE_SHADER_STAGE_CREATE_INFO,
    PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
    PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
    PIPELINE_TESSELLATION_STATE_CREATE_INFO,
    PIPELINE_VIEWPORT_STATE_CREATE_INFO,
    PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
    PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
    PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,
    PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
    PIPELINE_DYNAMIC_STATE_CREATE_INFO,
    GRAPHICS_PIPELINE_CREATE_INFO,
    COMPUTE_PIPELINE_CREATE_INFO,
    PIPELINE_LAYOUT_CREATE_INFO,
    SAMPLER_CREATE_INFO,
    DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
    DESCRIPTOR_POOL_CREATE_INFO,
    DESCRIPTOR_SET_ALLOCATE_INFO,
    WRITE_DESCRIPTOR_SET,
    COPY_DESCRIPTOR_SET,
    FRAMEBUFFER_CREATE_INFO,
    RENDER_PASS_CREATE_INFO,
    COMMAND_POOL_CREATE_INFO,
    COMMAND_BUFFER_ALLOCATE_INFO,
    COMMAND_BUFFER_INHERITANCE_INFO,
    COMMAND_BUFFER_BEGIN_INFO,
    RENDER_PASS_BEGIN_INFO,
    BUFFER_MEMORY_BARRIER,
    IMAGE_MEMORY_BARRIER,
    MEMORY_BARRIER,
    LOADER_INSTANCE_CREATE_INFO,
    LOADER_DEVICE_CREATE_INFO,
    PHYSICAL_DEVICE_SUBGROUP_PROPERTIES,
    BIND_BUFFER_MEMORY_INFO,
    BIND_IMAGE_MEMORY_INFO,
    PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES,
    MEMORY_DEDICATED_REQUIREMENTS,
    MEMORY_DEDICATED_ALLOCATE_INFO,
    MEMORY_ALLOCATE_FLAGS_INFO,
    DEVICE_GROUP_RENDER_PASS_BEGIN_INFO,
    DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO,
    DEVICE_GROUP_SUBMIT_INFO,
    DEVICE_GROUP_BIND_SPARSE_INFO,
    BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO,
    BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO,
    PHYSICAL_DEVICE_GROUP_PROPERTIES,
    DEVICE_GROUP_DEVICE_CREATE_INFO,
    BUFFER_MEMORY_REQUIREMENTS_INFO_2,
    IMAGE_MEMORY_REQUIREMENTS_INFO_2,
    IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2,
    MEMORY_REQUIREMENTS_2,
    SPARSE_IMAGE_MEMORY_REQUIREMENTS_2,
    PHYSICAL_DEVICE_FEATURES_2,
    PHYSICAL_DEVICE_PROPERTIES_2,
    FORMAT_PROPERTIES_2,
    IMAGE_FORMAT_PROPERTIES_2,
    PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2,
    QUEUE_FAMILY_PROPERTIES_2,
    PHYSICAL_DEVICE_MEMORY_PROPERTIES_2,
    SPARSE_IMAGE_FORMAT_PROPERTIES_2,
    PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2,
    PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES,
    RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO,
    IMAGE_VIEW_USAGE_CREATE_INFO,
    PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO,
    RENDER_PASS_MULTIVIEW_CREATE_INFO,
    PHYSICAL_DEVICE_MULTIVIEW_FEATURES,
    PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES,
    PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES,
    PROTECTED_SUBMIT_INFO,
    PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES,
    PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES,
    DEVICE_QUEUE_INFO_2,
    SAMPLER_YCBCR_CONVERSION_CREATE_INFO,
    SAMPLER_YCBCR_CONVERSION_INFO,
    BIND_IMAGE_PLANE_MEMORY_INFO,
    IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO,
    PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES,
    SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES,
    DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO,
    PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO,
    EXTERNAL_IMAGE_FORMAT_PROPERTIES,
    PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO,
    EXTERNAL_BUFFER_PROPERTIES,
    PHYSICAL_DEVICE_ID_PROPERTIES,
    EXTERNAL_MEMORY_BUFFER_CREATE_INFO,
    EXTERNAL_MEMORY_IMAGE_CREATE_INFO,
    EXPORT_MEMORY_ALLOCATE_INFO,
    PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO,
    EXTERNAL_FENCE_PROPERTIES,
    EXPORT_FENCE_CREATE_INFO,
    EXPORT_SEMAPHORE_CREATE_INFO,
    PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO,
    EXTERNAL_SEMAPHORE_PROPERTIES,
    PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES,
    DESCRIPTOR_SET_LAYOUT_SUPPORT,
    PHYSICAL_DEVICE_SHADER_DRAW_PARAMETER_FEATURES,
    SWAPCHAIN_CREATE_INFO,
    PRESENT_INFO,
    DEVICE_GROUP_PRESENT_CAPABILITIES,
    IMAGE_SWAPCHAIN_CREATE_INFO,
    BIND_IMAGE_MEMORY_SWAPCHAIN_INFO,
    ACQUIRE_NEXT_IMAGE_INFO,
    DEVICE_GROUP_PRESENT_INFO,
    DEVICE_GROUP_SWAPCHAIN_CREATE_INFO,
    DISPLAY_MODE_CREATE_INFO,
    DISPLAY_SURFACE_CREATE_INFO,
    DISPLAY_PRESENT_INFO,
    XLIB_SURFACE_CREATE_INFO,
    XCB_SURFACE_CREATE_INFO,
    WAYLAND_SURFACE_CREATE_INFO,
    ANDROID_SURFACE_CREATE_INFO,
    WIN32_SURFACE_CREATE_INFO,
    DEBUG_REPORT_CALLBACK_CREATE_INFO,
    PIPELINE_RASTERIZATION_STATE_RASTERIZATION_ORDER_AMD,
    DEBUG_MARKER_OBJECT_NAME_INFO,
    DEBUG_MARKER_OBJECT_TAG_INFO,
    DEBUG_MARKER_MARKER_INFO,
    DEDICATED_ALLOCATION_IMAGE_CREATE_INFO_NV,
    DEDICATED_ALLOCATION_BUFFER_CREATE_INFO_NV,
    DEDICATED_ALLOCATION_MEMORY_ALLOCATE_INFO_NV,
    PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_FEATURES,
    PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_PROPERTIES,
    PIPELINE_RASTERIZATION_STATE_STREAM_CREATE_INFO,
    TEXTURE_LOD_GATHER_FORMAT_PROPERTIES_AMD,
    PHYSICAL_DEVICE_CORNER_SAMPLED_IMAGE_FEATURES_NV,
    EXTERNAL_MEMORY_IMAGE_CREATE_INFO_NV,
    EXPORT_MEMORY_ALLOCATE_INFO_NV,
    IMPORT_MEMORY_WIN32_HANDLE_INFO_NV,
    EXPORT_MEMORY_WIN32_HANDLE_INFO_NV,
    WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_NV,
    VALIDATION_FLAGS,
    VI_SURFACE_CREATE_INFO_NN,
    IMAGE_VIEW_ASTC_DECODE_MODE,
    PHYSICAL_DEVICE_ASTC_DECODE_FEATURES,
    IMPORT_MEMORY_WIN32_HANDLE_INFO,
    EXPORT_MEMORY_WIN32_HANDLE_INFO,
    MEMORY_WIN32_HANDLE_PROPERTIES,
    MEMORY_GET_WIN32_HANDLE_INFO,
    IMPORT_MEMORY_FD_INFO,
    MEMORY_FD_PROPERTIES,
    MEMORY_GET_FD_INFO,
    WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO,
    IMPORT_SEMAPHORE_WIN32_HANDLE_INFO,
    EXPORT_SEMAPHORE_WIN32_HANDLE_INFO,
    D3D12_FENCE_SUBMIT_INFO,
    SEMAPHORE_GET_WIN32_HANDLE_INFO,
    IMPORT_SEMAPHORE_FD_INFO,
    SEMAPHORE_GET_FD_INFO,
    PHYSICAL_DEVICE_PUSH_DESCRIPTOR_PROPERTIES,
    COMMAND_BUFFER_INHERITANCE_CONDITIONAL_RENDERING_INFO,
    PHYSICAL_DEVICE_CONDITIONAL_RENDERING_FEATURES,
    CONDITIONAL_RENDERING_BEGIN_INFO,
    PHYSICAL_DEVICE_FLOAT16_INT8_FEATURES,
    PRESENT_REGIONS,
    OBJECT_TABLE_CREATE_INFO_NVX,
    INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_NVX,
    CMD_PROCESS_COMMANDS_INFO_NVX,
    CMD_RESERVE_SPACE_FOR_COMMANDS_INFO_NVX,
    DEVICE_GENERATED_COMMANDS_LIMITS_NVX,
    DEVICE_GENERATED_COMMANDS_FEATURES_NVX,
    PIPELINE_VIEWPORT_W_SCALING_STATE_CREATE_INFO_NV,
    SURFACE_CAPABILITIES_2,
    DISPLAY_POWER_INFO,
    DEVICE_EVENT_INFO,
    DISPLAY_EVENT_INFO,
    SWAPCHAIN_COUNTER_CREATE_INFO,
    PRESENT_TIMES_INFO_GOOGLE,
    PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_ATTRIBUTES_PROPERTIES_NVX,
    PIPELINE_VIEWPORT_SWIZZLE_STATE_CREATE_INFO_NV,
    PHYSICAL_DEVICE_DISCARD_RECTANGLE_PROPERTIES,
    PIPELINE_DISCARD_RECTANGLE_STATE_CREATE_INFO,
    PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES,
    PIPELINE_RASTERIZATION_CONSERVATIVE_STATE_CREATE_INFO,
    PHYSICAL_DEVICE_DEPTH_CLIP_ENABLE_FEATURES,
    PIPELINE_RASTERIZATION_DEPTH_CLIP_STATE_CREATE_INFO,
    HDR_METADATA,
    ATTACHMENT_DESCRIPTION_2,
    ATTACHMENT_REFERENCE_2,
    SUBPASS_DESCRIPTION_2,
    SUBPASS_DEPENDENCY_2,
    RENDER_PASS_CREATE_INFO_2,
    SUBPASS_BEGIN_INFO,
    SUBPASS_END_INFO,
    SHARED_PRESENT_SURFACE_CAPABILITIES,
    IMPORT_FENCE_WIN32_HANDLE_INFO,
    EXPORT_FENCE_WIN32_HANDLE_INFO,
    FENCE_GET_WIN32_HANDLE_INFO,
    IMPORT_FENCE_FD_INFO,
    FENCE_GET_FD_INFO,
    PHYSICAL_DEVICE_SURFACE_INFO_2,
    SURFACE_FORMAT_2,
    DISPLAY_PROPERTIES_2,
    DISPLAY_PLANE_PROPERTIES_2,
    DISPLAY_MODE_PROPERTIES_2,
    DISPLAY_PLANE_INFO_2,
    DISPLAY_PLANE_CAPABILITIES_2,
    IOS_SURFACE_CREATE_INFO_MVK,
    MACOS_SURFACE_CREATE_INFO_MVK,
    DEBUG_UTILS_OBJECT_NAME_INFO,
    DEBUG_UTILS_OBJECT_TAG_INFO,
    DEBUG_UTILS_LABEL,
    DEBUG_UTILS_MESSENGER_CALLBACK_DATA,
    DEBUG_UTILS_MESSENGER_CREATE_INFO,
    ANDROID_HARDWARE_BUFFER_USAGE_ANDROID,
    ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID,
    ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID,
    IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID,
    MEMORY_GET_ANDROID_HARDWARE_BUFFER_INFO_ANDROID,
    EXTERNAL_FORMAT_ANDROID,
    PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES,
    SAMPLER_REDUCTION_MODE_CREATE_INFO,
    PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES,
    PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES,
    WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK,
    DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO,
    SAMPLE_LOCATIONS_INFO,
    RENDER_PASS_SAMPLE_LOCATIONS_BEGIN_INFO,
    PIPELINE_SAMPLE_LOCATIONS_STATE_CREATE_INFO,
    PHYSICAL_DEVICE_SAMPLE_LOCATIONS_PROPERTIES,
    MULTISAMPLE_PROPERTIES,
    IMAGE_FORMAT_LIST_CREATE_INFO,
    PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_FEATURES,
    PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_PROPERTIES,
    PIPELINE_COLOR_BLEND_ADVANCED_STATE_CREATE_INFO,
    PIPELINE_COVERAGE_TO_COLOR_STATE_CREATE_INFO_NV,
    PIPELINE_COVERAGE_MODULATION_STATE_CREATE_INFO_NV,
    DRM_FORMAT_MODIFIER_PROPERTIES_LIST,
    DRM_FORMAT_MODIFIER_PROPERTIES,
    PHYSICAL_DEVICE_IMAGE_DRM_FORMAT_MODIFIER_INFO,
    IMAGE_DRM_FORMAT_MODIFIER_LIST_CREATE_INFO,
    IMAGE_DRM_FORMAT_MODIFIER_EXPLICIT_CREATE_INFO,
    IMAGE_DRM_FORMAT_MODIFIER_PROPERTIES,
    VALIDATION_CACHE_CREATE_INFO,
    SHADER_MODULE_VALIDATION_CACHE_CREATE_INFO,
    DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO,
    PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES,
    PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES,
    DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO,
    DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT,
    PIPELINE_VIEWPORT_SHADING_RATE_IMAGE_STATE_CREATE_INFO_NV,
    PHYSICAL_DEVICE_SHADING_RATE_IMAGE_FEATURES_NV,
    PHYSICAL_DEVICE_SHADING_RATE_IMAGE_PROPERTIES_NV,
    PIPELINE_VIEWPORT_COARSE_SAMPLE_ORDER_STATE_CREATE_INFO_NV,
    RAY_TRACING_PIPELINE_CREATE_INFO_NV,
    ACCELERATION_STRUCTURE_CREATE_INFO_NV,
    GEOMETRY_NV,
    GEOMETRY_TRIANGLES_NV,
    GEOMETRY_AABB_NV,
    BIND_ACCELERATION_STRUCTURE_MEMORY_INFO_NV,
    WRITE_DESCRIPTOR_SET_ACCELERATION_STRUCTURE_NV,
    ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_INFO_NV,
    PHYSICAL_DEVICE_RAY_TRACING_PROPERTIES_NV,
    RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV,
    ACCELERATION_STRUCTURE_INFO_NV,
    PHYSICAL_DEVICE_REPRESENTATIVE_FRAGMENT_TEST_FEATURES_NV,
    PIPELINE_REPRESENTATIVE_FRAGMENT_TEST_STATE_CREATE_INFO_NV,
    PHYSICAL_DEVICE_IMAGE_VIEW_IMAGE_FORMAT_INFO,
    FILTER_CUBIC_IMAGE_VIEW_IMAGE_FORMAT_PROPERTIES,
    DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO,
    PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES,
    IMPORT_MEMORY_HOST_POINTER_INFO,
    MEMORY_HOST_POINTER_PROPERTIES,
    PHYSICAL_DEVICE_EXTERNAL_MEMORY_HOST_PROPERTIES,
    PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES,
    CALIBRATED_TIMESTAMP_INFO,
    PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_AMD,
    DEVICE_MEMORY_OVERALLOCATION_CREATE_INFO_AMD,
    PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES,
    PIPELINE_VERTEX_INPUT_DIVISOR_STATE_CREATE_INFO,
    PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_FEATURES,
    PHYSICAL_DEVICE_DRIVER_PROPERTIES,
    PHYSICAL_DEVICE_FLOAT_CONTROLS_PROPERTIES,
    PHYSICAL_DEVICE_DEPTH_STENCIL_RESOLVE_PROPERTIES,
    SUBPASS_DESCRIPTION_DEPTH_STENCIL_RESOLVE,
    PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_FEATURES_NV,
    PHYSICAL_DEVICE_MESH_SHADER_FEATURES_NV,
    PHYSICAL_DEVICE_MESH_SHADER_PROPERTIES_NV,
    PHYSICAL_DEVICE_FRAGMENT_SHADER_BARYCENTRIC_FEATURES_NV,
    PHYSICAL_DEVICE_SHADER_IMAGE_FOOTPRINT_FEATURES_NV,
    PIPELINE_VIEWPORT_EXCLUSIVE_SCISSOR_STATE_CREATE_INFO_NV,
    PHYSICAL_DEVICE_EXCLUSIVE_SCISSOR_FEATURES_NV,
    CHECKPOINT_DATA_NV,
    QUEUE_FAMILY_CHECKPOINT_PROPERTIES_NV,
    PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES,
    PHYSICAL_DEVICE_PCI_BUS_INFO_PROPERTIES,
    IMAGEPIPE_SURFACE_CREATE_INFO_FUCHSIA,
    PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_FEATURES,
    PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_PROPERTIES,
    RENDER_PASS_FRAGMENT_DENSITY_MAP_CREATE_INFO,
    PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES,
    PHYSICAL_DEVICE_MEMORY_BUDGET_PROPERTIES,
    PHYSICAL_DEVICE_MEMORY_PRIORITY_FEATURES,
    MEMORY_PRIORITY_ALLOCATE_INFO,
    PHYSICAL_DEVICE_DEDICATED_ALLOCATION_IMAGE_ALIASING_FEATURES_NV,
    PHYSICAL_DEVICE_BUFFER_ADDRESS_FEATURES,
    BUFFER_DEVICE_ADDRESS_INFO,
    BUFFER_DEVICE_ADDRESS_CREATE_INFO,
    IMAGE_STENCIL_USAGE_CREATE_INFO,
    VALIDATION_FEATURES,
    PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV,
    COOPERATIVE_MATRIX_PROPERTIES_NV,
    PHYSICAL_DEVICE_COOPERATIVE_MATRIX_PROPERTIES_NV,
    DEBUG_REPORT_CREATE_INFO,
    SURFACE_CAPABILITIES2;

    public static VulkanStructureType fromNativeEnum(VkStructureType e){
        switch(e.value){
            case VkStructureType.VK_STRUCTURE_TYPE_APPLICATION_INFO: return APPLICATION_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO: return INSTANCE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO: return DEVICE_QUEUE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO: return DEVICE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SUBMIT_INFO: return SUBMIT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO: return MEMORY_ALLOCATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE: return MAPPED_MEMORY_RANGE;
            case VkStructureType.VK_STRUCTURE_TYPE_BIND_SPARSE_INFO: return BIND_SPARSE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_FENCE_CREATE_INFO: return FENCE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO: return SEMAPHORE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EVENT_CREATE_INFO: return EVENT_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO: return QUERY_POOL_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO: return BUFFER_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO: return BUFFER_VIEW_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO: return IMAGE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO: return IMAGE_VIEW_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO: return SHADER_MODULE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO: return PIPELINE_CACHE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO: return PIPELINE_SHADER_STAGE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO: return PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO: return PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO: return PIPELINE_TESSELLATION_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO: return PIPELINE_VIEWPORT_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO: return PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO: return PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO: return PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO: return PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO: return PIPELINE_DYNAMIC_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO: return GRAPHICS_PIPELINE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO: return COMPUTE_PIPELINE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO: return PIPELINE_LAYOUT_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO: return SAMPLER_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO: return DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO: return DESCRIPTOR_POOL_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO: return DESCRIPTOR_SET_ALLOCATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET: return WRITE_DESCRIPTOR_SET;
            case VkStructureType.VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET: return COPY_DESCRIPTOR_SET;
            case VkStructureType.VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO: return FRAMEBUFFER_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO: return RENDER_PASS_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO: return COMMAND_POOL_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO: return COMMAND_BUFFER_ALLOCATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO: return COMMAND_BUFFER_INHERITANCE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO: return COMMAND_BUFFER_BEGIN_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO: return RENDER_PASS_BEGIN_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER: return BUFFER_MEMORY_BARRIER;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER: return IMAGE_MEMORY_BARRIER;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_BARRIER: return MEMORY_BARRIER;
            case VkStructureType.VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO: return LOADER_INSTANCE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO: return LOADER_DEVICE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES: return PHYSICAL_DEVICE_SUBGROUP_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO: return PROTECTED_SUBMIT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES: return PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES: return PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_QUEUE_INFO_2: return DEVICE_QUEUE_INFO_2;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETER_FEATURES: return PHYSICAL_DEVICE_SHADER_DRAW_PARAMETER_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR: return SWAPCHAIN_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PRESENT_INFO_KHR: return PRESENT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_CAPABILITIES_KHR: return DEVICE_GROUP_PRESENT_CAPABILITIES;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_SWAPCHAIN_CREATE_INFO_KHR: return IMAGE_SWAPCHAIN_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_SWAPCHAIN_INFO_KHR: return BIND_IMAGE_MEMORY_SWAPCHAIN_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_ACQUIRE_NEXT_IMAGE_INFO_KHR: return ACQUIRE_NEXT_IMAGE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_INFO_KHR: return DEVICE_GROUP_PRESENT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GROUP_SWAPCHAIN_CREATE_INFO_KHR: return DEVICE_GROUP_SWAPCHAIN_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_MODE_CREATE_INFO_KHR: return DISPLAY_MODE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_SURFACE_CREATE_INFO_KHR: return DISPLAY_SURFACE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_PRESENT_INFO_KHR: return DISPLAY_PRESENT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR: return XLIB_SURFACE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR: return XCB_SURFACE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR: return WAYLAND_SURFACE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR: return ANDROID_SURFACE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR: return WIN32_SURFACE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_RASTERIZATION_ORDER_AMD: return PIPELINE_RASTERIZATION_STATE_RASTERIZATION_ORDER_AMD;
            case VkStructureType.VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_NAME_INFO_EXT: return DEBUG_MARKER_OBJECT_NAME_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_TAG_INFO_EXT: return DEBUG_MARKER_OBJECT_TAG_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEBUG_MARKER_MARKER_INFO_EXT: return DEBUG_MARKER_MARKER_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_IMAGE_CREATE_INFO_NV: return DEDICATED_ALLOCATION_IMAGE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_BUFFER_CREATE_INFO_NV: return DEDICATED_ALLOCATION_BUFFER_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_MEMORY_ALLOCATE_INFO_NV: return DEDICATED_ALLOCATION_MEMORY_ALLOCATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_FEATURES_EXT: return PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_PROPERTIES_EXT: return PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_STREAM_CREATE_INFO_EXT: return PIPELINE_RASTERIZATION_STATE_STREAM_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_TEXTURE_LOD_GATHER_FORMAT_PROPERTIES_AMD: return TEXTURE_LOD_GATHER_FORMAT_PROPERTIES_AMD;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CORNER_SAMPLED_IMAGE_FEATURES_NV: return PHYSICAL_DEVICE_CORNER_SAMPLED_IMAGE_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO_NV: return EXTERNAL_MEMORY_IMAGE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO_NV: return EXPORT_MEMORY_ALLOCATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_NV: return IMPORT_MEMORY_WIN32_HANDLE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_NV: return EXPORT_MEMORY_WIN32_HANDLE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_NV: return WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_VALIDATION_FLAGS_EXT: return VALIDATION_FLAGS;
            case VkStructureType.VK_STRUCTURE_TYPE_VI_SURFACE_CREATE_INFO_NN: return VI_SURFACE_CREATE_INFO_NN;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_VIEW_ASTC_DECODE_MODE_EXT: return IMAGE_VIEW_ASTC_DECODE_MODE;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ASTC_DECODE_FEATURES_EXT: return PHYSICAL_DEVICE_ASTC_DECODE_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_KHR: return IMPORT_MEMORY_WIN32_HANDLE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_KHR: return EXPORT_MEMORY_WIN32_HANDLE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_WIN32_HANDLE_PROPERTIES_KHR: return MEMORY_WIN32_HANDLE_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_GET_WIN32_HANDLE_INFO_KHR: return MEMORY_GET_WIN32_HANDLE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMPORT_MEMORY_FD_INFO_KHR: return IMPORT_MEMORY_FD_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_FD_PROPERTIES_KHR: return MEMORY_FD_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR: return MEMORY_GET_FD_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_KHR: return WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMPORT_SEMAPHORE_WIN32_HANDLE_INFO_KHR: return IMPORT_SEMAPHORE_WIN32_HANDLE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_WIN32_HANDLE_INFO_KHR: return EXPORT_SEMAPHORE_WIN32_HANDLE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_D3D12_FENCE_SUBMIT_INFO_KHR: return D3D12_FENCE_SUBMIT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SEMAPHORE_GET_WIN32_HANDLE_INFO_KHR: return SEMAPHORE_GET_WIN32_HANDLE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMPORT_SEMAPHORE_FD_INFO_KHR: return IMPORT_SEMAPHORE_FD_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SEMAPHORE_GET_FD_INFO_KHR: return SEMAPHORE_GET_FD_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PUSH_DESCRIPTOR_PROPERTIES_KHR: return PHYSICAL_DEVICE_PUSH_DESCRIPTOR_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_CONDITIONAL_RENDERING_INFO_EXT: return COMMAND_BUFFER_INHERITANCE_CONDITIONAL_RENDERING_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONDITIONAL_RENDERING_FEATURES_EXT: return PHYSICAL_DEVICE_CONDITIONAL_RENDERING_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_CONDITIONAL_RENDERING_BEGIN_INFO_EXT: return CONDITIONAL_RENDERING_BEGIN_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FLOAT16_INT8_FEATURES_KHR: return PHYSICAL_DEVICE_FLOAT16_INT8_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PRESENT_REGIONS_KHR: return PRESENT_REGIONS;
            case VkStructureType.VK_STRUCTURE_TYPE_OBJECT_TABLE_CREATE_INFO_NVX: return OBJECT_TABLE_CREATE_INFO_NVX;
            case VkStructureType.VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_NVX: return INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_NVX;
            case VkStructureType.VK_STRUCTURE_TYPE_CMD_PROCESS_COMMANDS_INFO_NVX: return CMD_PROCESS_COMMANDS_INFO_NVX;
            case VkStructureType.VK_STRUCTURE_TYPE_CMD_RESERVE_SPACE_FOR_COMMANDS_INFO_NVX: return CMD_RESERVE_SPACE_FOR_COMMANDS_INFO_NVX;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GENERATED_COMMANDS_LIMITS_NVX: return DEVICE_GENERATED_COMMANDS_LIMITS_NVX;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GENERATED_COMMANDS_FEATURES_NVX: return DEVICE_GENERATED_COMMANDS_FEATURES_NVX;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_W_SCALING_STATE_CREATE_INFO_NV: return PIPELINE_VIEWPORT_W_SCALING_STATE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_POWER_INFO_EXT: return DISPLAY_POWER_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_EVENT_INFO_EXT: return DEVICE_EVENT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_EVENT_INFO_EXT: return DISPLAY_EVENT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SWAPCHAIN_COUNTER_CREATE_INFO_EXT: return SWAPCHAIN_COUNTER_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE: return PRESENT_TIMES_INFO_GOOGLE;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_ATTRIBUTES_PROPERTIES_NVX: return PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_ATTRIBUTES_PROPERTIES_NVX;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_SWIZZLE_STATE_CREATE_INFO_NV: return PIPELINE_VIEWPORT_SWIZZLE_STATE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DISCARD_RECTANGLE_PROPERTIES_EXT: return PHYSICAL_DEVICE_DISCARD_RECTANGLE_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_DISCARD_RECTANGLE_STATE_CREATE_INFO_EXT: return PIPELINE_DISCARD_RECTANGLE_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES_EXT: return PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_CONSERVATIVE_STATE_CREATE_INFO_EXT: return PIPELINE_RASTERIZATION_CONSERVATIVE_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLIP_ENABLE_FEATURES_EXT: return PHYSICAL_DEVICE_DEPTH_CLIP_ENABLE_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_DEPTH_CLIP_STATE_CREATE_INFO_EXT: return PIPELINE_RASTERIZATION_DEPTH_CLIP_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_HDR_METADATA_EXT: return HDR_METADATA;
            case VkStructureType.VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2_KHR: return ATTACHMENT_DESCRIPTION_2;
            case VkStructureType.VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2_KHR: return ATTACHMENT_REFERENCE_2;
            case VkStructureType.VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2_KHR: return SUBPASS_DESCRIPTION_2;
            case VkStructureType.VK_STRUCTURE_TYPE_SUBPASS_DEPENDENCY_2_KHR: return SUBPASS_DEPENDENCY_2;
            case VkStructureType.VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2_KHR: return RENDER_PASS_CREATE_INFO_2;
            case VkStructureType.VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO_KHR: return SUBPASS_BEGIN_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SUBPASS_END_INFO_KHR: return SUBPASS_END_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SHARED_PRESENT_SURFACE_CAPABILITIES_KHR: return SHARED_PRESENT_SURFACE_CAPABILITIES;
            case VkStructureType.VK_STRUCTURE_TYPE_IMPORT_FENCE_WIN32_HANDLE_INFO_KHR: return IMPORT_FENCE_WIN32_HANDLE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EXPORT_FENCE_WIN32_HANDLE_INFO_KHR: return EXPORT_FENCE_WIN32_HANDLE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_FENCE_GET_WIN32_HANDLE_INFO_KHR: return FENCE_GET_WIN32_HANDLE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMPORT_FENCE_FD_INFO_KHR: return IMPORT_FENCE_FD_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_FENCE_GET_FD_INFO_KHR: return FENCE_GET_FD_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SURFACE_INFO_2_KHR: return PHYSICAL_DEVICE_SURFACE_INFO_2;
            case VkStructureType.VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES_2_KHR: return SURFACE_CAPABILITIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR: return SURFACE_FORMAT_2;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_PROPERTIES_2_KHR: return DISPLAY_PROPERTIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_PLANE_PROPERTIES_2_KHR: return DISPLAY_PLANE_PROPERTIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_MODE_PROPERTIES_2_KHR: return DISPLAY_MODE_PROPERTIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_PLANE_INFO_2_KHR: return DISPLAY_PLANE_INFO_2;
            case VkStructureType.VK_STRUCTURE_TYPE_DISPLAY_PLANE_CAPABILITIES_2_KHR: return DISPLAY_PLANE_CAPABILITIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_IOS_SURFACE_CREATE_INFO_MVK: return IOS_SURFACE_CREATE_INFO_MVK;
            case VkStructureType.VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK: return MACOS_SURFACE_CREATE_INFO_MVK;
            case VkStructureType.VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT: return DEBUG_UTILS_OBJECT_NAME_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_TAG_INFO_EXT: return DEBUG_UTILS_OBJECT_TAG_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT: return DEBUG_UTILS_LABEL;
            case VkStructureType.VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT: return DEBUG_UTILS_MESSENGER_CALLBACK_DATA;
            case VkStructureType.VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT: return DEBUG_UTILS_MESSENGER_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_USAGE_ANDROID: return ANDROID_HARDWARE_BUFFER_USAGE_ANDROID;
            case VkStructureType.VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID: return ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID;
            case VkStructureType.VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID: return ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID;
            case VkStructureType.VK_STRUCTURE_TYPE_IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID: return IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_GET_ANDROID_HARDWARE_BUFFER_INFO_ANDROID: return MEMORY_GET_ANDROID_HARDWARE_BUFFER_INFO_ANDROID;
            case VkStructureType.VK_STRUCTURE_TYPE_EXTERNAL_FORMAT_ANDROID: return EXTERNAL_FORMAT_ANDROID;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES_EXT: return PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO_EXT: return SAMPLER_REDUCTION_MODE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES_EXT: return PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES_EXT: return PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK_EXT: return WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK;
            case VkStructureType.VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO_EXT: return DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SAMPLE_LOCATIONS_INFO_EXT: return SAMPLE_LOCATIONS_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_RENDER_PASS_SAMPLE_LOCATIONS_BEGIN_INFO_EXT: return RENDER_PASS_SAMPLE_LOCATIONS_BEGIN_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_SAMPLE_LOCATIONS_STATE_CREATE_INFO_EXT: return PIPELINE_SAMPLE_LOCATIONS_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLE_LOCATIONS_PROPERTIES_EXT: return PHYSICAL_DEVICE_SAMPLE_LOCATIONS_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_MULTISAMPLE_PROPERTIES_EXT: return MULTISAMPLE_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO_KHR: return IMAGE_FORMAT_LIST_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_FEATURES_EXT: return PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_PROPERTIES_EXT: return PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_ADVANCED_STATE_CREATE_INFO_EXT: return PIPELINE_COLOR_BLEND_ADVANCED_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_COVERAGE_TO_COLOR_STATE_CREATE_INFO_NV: return PIPELINE_COVERAGE_TO_COLOR_STATE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_COVERAGE_MODULATION_STATE_CREATE_INFO_NV: return PIPELINE_COVERAGE_MODULATION_STATE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_DRM_FORMAT_MODIFIER_PROPERTIES_LIST_EXT: return DRM_FORMAT_MODIFIER_PROPERTIES_LIST;
            case VkStructureType.VK_STRUCTURE_TYPE_DRM_FORMAT_MODIFIER_PROPERTIES_EXT: return DRM_FORMAT_MODIFIER_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_DRM_FORMAT_MODIFIER_INFO_EXT: return PHYSICAL_DEVICE_IMAGE_DRM_FORMAT_MODIFIER_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_DRM_FORMAT_MODIFIER_LIST_CREATE_INFO_EXT: return IMAGE_DRM_FORMAT_MODIFIER_LIST_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_DRM_FORMAT_MODIFIER_EXPLICIT_CREATE_INFO_EXT: return IMAGE_DRM_FORMAT_MODIFIER_EXPLICIT_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_DRM_FORMAT_MODIFIER_PROPERTIES_EXT: return IMAGE_DRM_FORMAT_MODIFIER_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_VALIDATION_CACHE_CREATE_INFO_EXT: return VALIDATION_CACHE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SHADER_MODULE_VALIDATION_CACHE_CREATE_INFO_EXT: return SHADER_MODULE_VALIDATION_CACHE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO_EXT: return DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES_EXT: return PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES_EXT: return PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO_EXT: return DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT_EXT: return DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_SHADING_RATE_IMAGE_STATE_CREATE_INFO_NV: return PIPELINE_VIEWPORT_SHADING_RATE_IMAGE_STATE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADING_RATE_IMAGE_FEATURES_NV: return PHYSICAL_DEVICE_SHADING_RATE_IMAGE_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADING_RATE_IMAGE_PROPERTIES_NV: return PHYSICAL_DEVICE_SHADING_RATE_IMAGE_PROPERTIES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_COARSE_SAMPLE_ORDER_STATE_CREATE_INFO_NV: return PIPELINE_VIEWPORT_COARSE_SAMPLE_ORDER_STATE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_RAY_TRACING_PIPELINE_CREATE_INFO_NV: return RAY_TRACING_PIPELINE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_CREATE_INFO_NV: return ACCELERATION_STRUCTURE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_GEOMETRY_NV: return GEOMETRY_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_GEOMETRY_TRIANGLES_NV: return GEOMETRY_TRIANGLES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_GEOMETRY_AABB_NV: return GEOMETRY_AABB_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_BIND_ACCELERATION_STRUCTURE_MEMORY_INFO_NV: return BIND_ACCELERATION_STRUCTURE_MEMORY_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_ACCELERATION_STRUCTURE_NV: return WRITE_DESCRIPTOR_SET_ACCELERATION_STRUCTURE_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_INFO_NV: return ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PROPERTIES_NV: return PHYSICAL_DEVICE_RAY_TRACING_PROPERTIES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV: return RAY_TRACING_SHADER_GROUP_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_INFO_NV: return ACCELERATION_STRUCTURE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_REPRESENTATIVE_FRAGMENT_TEST_FEATURES_NV: return PHYSICAL_DEVICE_REPRESENTATIVE_FRAGMENT_TEST_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_REPRESENTATIVE_FRAGMENT_TEST_STATE_CREATE_INFO_NV: return PIPELINE_REPRESENTATIVE_FRAGMENT_TEST_STATE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_VIEW_IMAGE_FORMAT_INFO_EXT: return PHYSICAL_DEVICE_IMAGE_VIEW_IMAGE_FORMAT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_FILTER_CUBIC_IMAGE_VIEW_IMAGE_FORMAT_PROPERTIES_EXT: return FILTER_CUBIC_IMAGE_VIEW_IMAGE_FORMAT_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO_EXT: return DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES_KHR: return PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_IMPORT_MEMORY_HOST_POINTER_INFO_EXT: return IMPORT_MEMORY_HOST_POINTER_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_HOST_POINTER_PROPERTIES_EXT: return MEMORY_HOST_POINTER_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_MEMORY_HOST_PROPERTIES_EXT: return PHYSICAL_DEVICE_EXTERNAL_MEMORY_HOST_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES_KHR: return PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_CALIBRATED_TIMESTAMP_INFO_EXT: return CALIBRATED_TIMESTAMP_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_AMD: return PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_AMD;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_MEMORY_OVERALLOCATION_CREATE_INFO_AMD: return DEVICE_MEMORY_OVERALLOCATION_CREATE_INFO_AMD;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES_EXT: return PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_DIVISOR_STATE_CREATE_INFO_EXT: return PIPELINE_VERTEX_INPUT_DIVISOR_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_FEATURES_EXT: return PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRIVER_PROPERTIES_KHR: return PHYSICAL_DEVICE_DRIVER_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FLOAT_CONTROLS_PROPERTIES_KHR: return PHYSICAL_DEVICE_FLOAT_CONTROLS_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_STENCIL_RESOLVE_PROPERTIES_KHR: return PHYSICAL_DEVICE_DEPTH_STENCIL_RESOLVE_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_DEPTH_STENCIL_RESOLVE_KHR: return SUBPASS_DESCRIPTION_DEPTH_STENCIL_RESOLVE;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_FEATURES_NV: return PHYSICAL_DEVICE_COMPUTE_SHADER_DERIVATIVES_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_FEATURES_NV: return PHYSICAL_DEVICE_MESH_SHADER_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_PROPERTIES_NV: return PHYSICAL_DEVICE_MESH_SHADER_PROPERTIES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_BARYCENTRIC_FEATURES_NV: return PHYSICAL_DEVICE_FRAGMENT_SHADER_BARYCENTRIC_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_IMAGE_FOOTPRINT_FEATURES_NV: return PHYSICAL_DEVICE_SHADER_IMAGE_FOOTPRINT_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_EXCLUSIVE_SCISSOR_STATE_CREATE_INFO_NV: return PIPELINE_VIEWPORT_EXCLUSIVE_SCISSOR_STATE_CREATE_INFO_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXCLUSIVE_SCISSOR_FEATURES_NV: return PHYSICAL_DEVICE_EXCLUSIVE_SCISSOR_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_CHECKPOINT_DATA_NV: return CHECKPOINT_DATA_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_QUEUE_FAMILY_CHECKPOINT_PROPERTIES_NV: return QUEUE_FAMILY_CHECKPOINT_PROPERTIES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES_KHR: return PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PCI_BUS_INFO_PROPERTIES_EXT: return PHYSICAL_DEVICE_PCI_BUS_INFO_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGEPIPE_SURFACE_CREATE_INFO_FUCHSIA: return IMAGEPIPE_SURFACE_CREATE_INFO_FUCHSIA;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_FEATURES_EXT: return PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_PROPERTIES_EXT: return PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_RENDER_PASS_FRAGMENT_DENSITY_MAP_CREATE_INFO_EXT: return RENDER_PASS_FRAGMENT_DENSITY_MAP_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES_EXT: return PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_BUDGET_PROPERTIES_EXT: return PHYSICAL_DEVICE_MEMORY_BUDGET_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PRIORITY_FEATURES_EXT: return PHYSICAL_DEVICE_MEMORY_PRIORITY_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_PRIORITY_ALLOCATE_INFO_EXT: return MEMORY_PRIORITY_ALLOCATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEDICATED_ALLOCATION_IMAGE_ALIASING_FEATURES_NV: return PHYSICAL_DEVICE_DEDICATED_ALLOCATION_IMAGE_ALIASING_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_ADDRESS_FEATURES_EXT: return PHYSICAL_DEVICE_BUFFER_ADDRESS_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO_EXT: return BUFFER_DEVICE_ADDRESS_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_CREATE_INFO_EXT: return BUFFER_DEVICE_ADDRESS_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO_EXT: return IMAGE_STENCIL_USAGE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT: return VALIDATION_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV: return PHYSICAL_DEVICE_COOPERATIVE_MATRIX_FEATURES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_COOPERATIVE_MATRIX_PROPERTIES_NV: return COOPERATIVE_MATRIX_PROPERTIES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_COOPERATIVE_MATRIX_PROPERTIES_NV: return PHYSICAL_DEVICE_COOPERATIVE_MATRIX_PROPERTIES_NV;
            case VkStructureType.VK_STRUCTURE_TYPE_DEBUG_REPORT_CREATE_INFO_EXT: return DEBUG_REPORT_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO_KHR: return RENDER_PASS_MULTIVIEW_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES_KHR: return PHYSICAL_DEVICE_MULTIVIEW_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES_KHR: return PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2_KHR: return PHYSICAL_DEVICE_FEATURES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHR: return PHYSICAL_DEVICE_PROPERTIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2_KHR: return FORMAT_PROPERTIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2_KHR: return IMAGE_FORMAT_PROPERTIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2_KHR: return PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2;
            case VkStructureType.VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2_KHR: return QUEUE_FAMILY_PROPERTIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2_KHR: return PHYSICAL_DEVICE_MEMORY_PROPERTIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2_KHR: return SPARSE_IMAGE_FORMAT_PROPERTIES_2;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2_KHR: return PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO_KHR: return MEMORY_ALLOCATE_FLAGS_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO_KHR: return DEVICE_GROUP_RENDER_PASS_BEGIN_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO_KHR: return DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO_KHR: return DEVICE_GROUP_SUBMIT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO_KHR: return DEVICE_GROUP_BIND_SPARSE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO_KHR: return BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO_KHR: return BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES_KHR: return PHYSICAL_DEVICE_GROUP_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO_KHR: return DEVICE_GROUP_DEVICE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO_KHR: return PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES_KHR: return EXTERNAL_IMAGE_FORMAT_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO_KHR: return PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES_KHR: return EXTERNAL_BUFFER_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES_KHR: return PHYSICAL_DEVICE_ID_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO_KHR: return EXTERNAL_MEMORY_BUFFER_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO_KHR: return EXTERNAL_MEMORY_IMAGE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO_KHR: return EXPORT_MEMORY_ALLOCATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO_KHR: return PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES_KHR: return EXTERNAL_SEMAPHORE_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO_KHR: return EXPORT_SEMAPHORE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES_KHR: return PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO_KHR: return DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES2_EXT: return SURFACE_CAPABILITIES2;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO_KHR: return PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES_KHR: return EXTERNAL_FENCE_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO_KHR: return EXPORT_FENCE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES_KHR: return PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO_KHR: return RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO_KHR: return IMAGE_VIEW_USAGE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO_KHR: return PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES_KHR: return PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS_KHR: return MEMORY_DEDICATED_REQUIREMENTS;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO_KHR: return MEMORY_DEDICATED_ALLOCATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2_KHR: return BUFFER_MEMORY_REQUIREMENTS_INFO_2;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2_KHR: return IMAGE_MEMORY_REQUIREMENTS_INFO_2;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2_KHR: return IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2;
            case VkStructureType.VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2_KHR: return MEMORY_REQUIREMENTS_2;
            case VkStructureType.VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2_KHR: return SPARSE_IMAGE_MEMORY_REQUIREMENTS_2;
            case VkStructureType.VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO_KHR: return SAMPLER_YCBCR_CONVERSION_CREATE_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO_KHR: return SAMPLER_YCBCR_CONVERSION_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO_KHR: return BIND_IMAGE_PLANE_MEMORY_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO_KHR: return IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES_KHR: return PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES;
            case VkStructureType.VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES_KHR: return SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO_KHR: return BIND_BUFFER_MEMORY_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO_KHR: return BIND_IMAGE_MEMORY_INFO;
            case VkStructureType.VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES_KHR: return PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES;
            case VkStructureType.VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT_KHR: return DESCRIPTOR_SET_LAYOUT_SUPPORT;
            default: return null;
        }
    }
}