
package cz.mg.transformator.vulkan;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;


public class StructureGenerator extends javax.swing.JFrame {

    public StructureGenerator() {
        initComponents();
    }

    private void generateSimple(){
        throw new UnsupportedOperationException();
    }
    
    /*
        public class VkPhysicalDeviceProperties extends Structure {
            public uint32_t apiVersion;
            public uint32_t driverVersion;
            public uint32_t vendorID;
            public uint32_t deviceID;
            public VkPhysicalDeviceType deviceType;
            public byte[] deviceName = new byte[VK_MAX_PHYSICAL_DEVICE_NAME_SIZE];
            public uint8_t[] pipelineCacheUUID = new uint8_t[VK_UUID_SIZE];
            public VkPhysicalDeviceLimits limits;
            public VkPhysicalDeviceSparseProperties sparseProperties;
    */
    private void generateComplex(){
        String input = jTextAreaInput.getText();
        String output = readAll();
        output = output.replace("OLD_NAME", genOldName(input));
        output = output.replace("NEW_NAME", genNewName(input));
        output = output.replace("GETTERS", genGetters(input));
        output = output.replace(" size_t ", " long ");
        output = output.replace(" int32_t ", " int ");
        output = output.replace(" uint32_t ", " int ");
        output = output.replace(" byte[] ", " String ");
        output = output.replace(" VkDeviceSize ", " long ");
        output = output.replace(" VkBool32 ", " boolean ");
        jTextAreaOutput.setText(output);
    }
    
    private String genOldName(String input){
        String[] lines = input.split("\\n");
        return lines[0].trim().split(" ")[2];
    }
    
    private String genNewName(String input){
        return genOldName(input).replace("Vk", "Vulkan");
    }
    
    private String genGetters(String input){
        String[] lines = input.split("\\n");
        String getters = "";
        for(int i = 1; i < lines.length; i++){
            String[] parts = lines[i].trim().split(" ");
            String type = parts[1];
            String tail = getTypeTail(type);
            String name = parts[2].replace(";", "");
            String get = type.equals("VkBool32") ? "is" : "get";
            String header = "    public " + type.replaceFirst("Vk", "Vulkan") + " " + get + capitalFirst(name) + "(){\n";
            String optionalNewBegin = type.startsWith("Vk") ? "new " + type.replaceFirst("Vk", "Vulkan") + "(" : "";
            String optionalNewEnd = type.startsWith("Vk") ? ")" : "";
            String body   = "        return " + optionalNewBegin + "structure." + name + tail + optionalNewEnd + ";\n";
            String footer = "    }\n\n";
            getters = getters + header + body + footer;
        }
        return getters;
    }
    
    private String readAll(){
        InputStream stream = getClass().getResourceAsStream("StructureSample.txt");
        try(BufferedReader reader = new BufferedReader(new InputStreamReader(stream))){
            String line;
            String content = "";
            while((line = reader.readLine()) != null){
                content = content + line + "\n";
            }
            return content;
        } catch (IOException ex) {
            throw new RuntimeException();
        }
    }
    
    private String getTypeTail(String type){
        switch(type){
            case "size_t": return ".longValue()";
            case "int32_t": return ".intValue()";
            case "uint32_t": return ".intValue()";
            case "VkDeviceSize": return ".longValue()";
            case "VkBool32": return ".intValue() == VK_FALSE ? false : true";
            default: return "";
        }
    }
    
    private String capitalFirst(String name){
        return name.substring(0, 1).toUpperCase() + name.substring(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInput = new javax.swing.JTextArea();
        jButtonSimple = new javax.swing.JButton();
        jButtonComplex = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaInput.setColumns(20);
        jTextAreaInput.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInput);

        jButtonSimple.setText("simple");
        jButtonSimple.setEnabled(false);
        jButtonSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpleActionPerformed(evt);
            }
        });

        jButtonComplex.setText("complex");
        jButtonComplex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComplexActionPerformed(evt);
            }
        });

        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonComplex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSimple)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimple)
                    .addComponent(jButtonComplex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpleActionPerformed
        generateSimple();
    }//GEN-LAST:event_jButtonSimpleActionPerformed

    private void jButtonComplexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComplexActionPerformed
        generateComplex();
    }//GEN-LAST:event_jButtonComplexActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StructureGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StructureGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StructureGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StructureGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StructureGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComplex;
    private javax.swing.JButton jButtonSimple;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaInput;
    private javax.swing.JTextArea jTextAreaOutput;
    // End of variables declaration//GEN-END:variables
}
